# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-29 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_project_deploy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corl', models.CharField(max_length=128)),
            ],
        ),
    ]
