# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-29 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_crossdomain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossdomain',
            old_name='corl',
            new_name='cors',
        ),
    ]
