# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('react1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('logo', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='react1.Student')),
            ],
        ),
    ]
