# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=32)),
                ('single', models.BooleanField()),
            ],
        ),
    ]
