# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-09 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
